### ISSUE TITLE
MOCKUP PROYECTO  "CENTROS ECOTURISTICOS WEB 3.0"

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-10-mockup-de-aplicacion-web-3-equipo-7#1]
https://www.figma.com/file/tCHavCr60dtOCMrIjaXleJ/proyecto?node-id=135%3A23&t=LfL3jU1phgItmlBB-0

EQUIPO Numero 8.
Jaczibeth Cruz Ramirez
Irvin Jimenez Sanchez
Betsabe Aricel Castro Rodriguez

**Comment by Daisy-GonzalezLita12** [comment]
49 de 50

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
